### ISSUE TITLE
Collision for terrain collider

### ISSUE THREAD

**Issue by UnifiedMonkey** [letharqic/InstantPipes#3]
it just ignores terrain collision.
![image](https://github.com/leth4/InstantPipes/assets/139132798/1aaacc15-9623-4a74-9a2b-230e16b08de4)

**Comment by leth4** [comment]
Hi! If the pipe just goes directly to the target, it means it failed to find a way, not that it ignores the collision; there should also be a warning appearing in the inspector if the path wasn't found (also, I checked on my machine, it can detect terrain colliders).

Here's what you can do:

- Set the `Iterations` higher, that will make the algorithm try for longer before giving up
- Set the `Grid Size` higher, this way the algorithm can find a way with less iterations
- Tone down the `Chaos`, `Straight Priority` and `Near Obstacle Priority` values, those make it harder to find a way

Since the generator checks a lot of points to find a path, it makes it hard to cover long distances with just the default 1000 points. Your safest bet to make pipes cover long distances would be to increase the `Grid Size` (making checked points more far apart).

Please let me know how it went.
